### ISSUE TITLE
Property on derived interface

### ISSUE THREAD

**Issue by SebastienDegodez** [Catel/Catel.Fody#10]
### Steps to reproduce

1. Create an interface IChild implementing an other interface IParent
2. Create a ViewModel and a model property type IChild
3. Expose a property in IParent.

Platform: VisualStudio 2013
.NET version: .NET4.5.2

### Expected behaviour

As on the classes

### Actual behaviour

We have an error : 
Fody/Catel : The object reference is not defined ...

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. Do you have a simple repro? Then we can create a unit test and fix this.

**Comment by SergeyIlyin** [comment]
I have same error too:
Platform: VisualStudio 2017
.NET version: netstandard2.0

Project Refs:
Catel.Fody 2.18
Catel.Core (netstandard2.0 version)
```
public class SimpleClass:ModelBase
{
    public int Id { get; set; }
}
```

There no  compilation error with next config
```
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
    <Catel WeaveProperties="false" />
</Weavers>
```

**Comment by GeertvanHorrik** [comment]
Please try Build - 2.19.0-unstable.1, it should fix this. Thanks for reporting.

**Comment by SergeyIlyin** [comment]
There no errors with 2.19.0-unstable.1
Decompiled code is OK. Thanks.

**Comment by GeertvanHorrik** [comment]
Great, thanks for the feedback. Then I'll release 2.19 and close this ticket.
