### ISSUE TITLE
Building with WeaveArguments in Debug fails with 2.17.0

### ISSUE THREAD

**Issue by DanielKuehner** [Catel/Catel.Fody#12]
Hi Geert,

I just have updated Catel.Fody from v2.14.0 to v2.17.0 (Fody from v1.29.4 to v2.1.0) and got this error:

> [...]
2:     Fody/Catel:   Finished 'Catel' in 1867ms 
2:   Fody:   Adding weaving info
2:   Fody:   Finished in 1ms 
2:   Fody:   Writing assembly to 'D:\_git\K3PO\src\K3PO.Core\obj\x64\Debug\K3PO.Core.dll'.
2: Error  (0,0): Fody: An unhandled exception occurred:
Exception:
Value does not fall within the expected range.
StackTrace:
   at Mono.Cecil.Pdb.ISymUnmanagedWriter2.DefineLocalVariable2(String name, Int32 attributes, Int32 sigToken, Int32 addrKind, Int32 addr1, Int32 addr2, Int32 addr3, Int32 startOffset, Int32 endOffset)
   at Mono.Cecil.Pdb.NativePdbWriter.DefineScope(ScopeDebugInformation scope, MethodDebugInformation info, MetadataToken& import_parent)
   at Mono.Cecil.Pdb.NativePdbWriter.Write(MethodDebugInformation info)
   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 18
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 89
Source:
Mono.Cecil.Pdb
TargetSite:
Void DefineLocalVariable2(System.String, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32)
2:   Fody:   Finished Fody 2525ms.

I am in the beginning of finding the problem but I do not really know how und where to look.
But if I remove Catel from FodyWeavers it builds and no error occurs.
I also found you issue https://github.com/Fody/Fody/issues/312 but this one is different.

Perhaps you have any idea on how I can get more info on this?

**Comment by DanielKuehner** [comment]
I am now checking which weaving fails: https://catelproject.atlassian.net/wiki/display/CTL45/Catel.Fody

**Comment by DanielKuehner** [comment]
It seams to be **WeaveArguments**.

wow ... there are hundreds of them in my project. How will I find it oO

**Comment by DanielKuehner** [comment]
Some more info:
* Building fails with debug, not with release
* Only one of my projects fails, all other build

**Comment by DanielKuehner** [comment]
Renaming is your friend - found the problematic Argument method: IsNotNull()
I have 1612 uses ... that will be fun ;)

**Comment by DanielKuehner** [comment]
Got it :)

Steps to reproduce:
* Have class with a method and a parameter, use Argument.IsNotNull and have no further code in it:
`class A
{
  void a(object o)
  {
    Argument.IsNotNull(() => o);
  }
}`
* Enable Catel Fody waeving with **WeaveArguments**
* Build as debug

I could reproduce the failure with any other method. And so I could fix the problem by removing the call.

**Comment by GeertvanHorrik** [comment]
Nice, thanks for the hard work investigating this. We'll create a repro and fix it.

**Comment by GeertvanHorrik** [comment]
btw you can easily set msbuild output logging to normal instead of minimalistic and you should easily see what method is causing the error.

**Comment by GeertvanHorrik** [comment]
This issue sounded familiar: https://catelproject.atlassian.net/browse/CTL-1028

**Comment by GeertvanHorrik** [comment]
Hmmm, unit tests succeed in both debug & release mode.

**Comment by GeertvanHorrik** [comment]
See https://github.com/Catel/Catel.Fody/commit/a075dece2f66d3bc1942b0d5b08add2c77f0e443 for all details. Please let me know if you have a repro that actually fails for the unit tests.

**Comment by DanielKuehner** [comment]
Your welcome and thank you. Sry for the not working repro. I will check and look into this.
Yes, and I believe I had already found some similar bug but I did not find the issue.

**Comment by GeertvanHorrik** [comment]
I believe this was already introduced in an earlier version of Fody and we fixed it in 2.16, but apparently it has not been fixed. Another thing you could try is to make sure to clean your lib folder and restart all vs instances.

**Comment by DanielKuehner** [comment]
I could reproduce the error with a new class but within my project.
There is a message comming from Fody/Catel:

> 2:     Fody/Catel:   Method 'K3PO.Core.Factories.Class1.MethodA' no longer uses display class 'K3PO.Core.Factories.Class1.<>c__DisplayClass0_0', removing the display class from the method

Does this say something to you?

**Comment by DanielKuehner** [comment]
What do you mean by "restart all vs instances"?

**Comment by DanielKuehner** [comment]
I added the class to another project of mine and could also reproduce the bug.
Now I will create a new project and hope this will fail too.

**Comment by GeertvanHorrik** [comment]
> What do you mean by "restart all vs instances"?

Fody lives in msbuild, and it could be that old versions are kept in memory while updating fody (or weavers).

**Comment by DanielKuehner** [comment]
Ok, and where is this lib folder or how can I look up the folder?

**Comment by GeertvanHorrik** [comment]
It's the packages folder for nuget.

**Comment by DanielKuehner** [comment]
Ok, I will search for it.

But: I have created a new project and this fails too ->
[Catel.Fody.7z.zip](https://github.com/Catel/Catel.Fody/files/1121294/Catel.Fody.7z.zip)

**Comment by DanielKuehner** [comment]
Funny, sometime I am getting another error:

> 0: Fody.WeavingTask-Aufgabe
0:   Fody: Fody (version 2.1.0.0) Executing
0:   Fody: ProjectDirectory: 'D:\temp\Catel.Fody\GH0012\'.
0:   Fody: AssemblyPath: 'D:\temp\Catel.Fody\GH0012\obj\Debug\GH0012.exe'
0:   Fody: Found path to weavers file 'D:\temp\Catel.Fody\GH0012\FodyWeavers.xml'.
0: Error  (0,0): Fody: An unhandled exception occurred:
Exception:
Format of the executable (.exe) or library (.dll) is invalid.
StackTrace:
Server stack trace: 
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at IsolatedContainsTypeChecker.Check(String assemblyPath, String typeName) in C:\projects\fody\FodyIsolated\IsolatedContainsTypeChecker.cs:line 20
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at IContainsTypeChecker.Check(String assemblyPath, String typeName)
   at ContainsTypeChecker.Check(String assemblyPath, String typeName) in C:\projects\fody\Fody\ContainsTypeChecker.cs:line 28
   at Processor.ShouldStartSinceFileChanged() in C:\projects\fody\Fody\FileChangedChecker.cs:line 6
   at Processor.Inner() in C:\projects\fody\Fody\Processor.cs:line 70
   at Processor.Execute() in C:\projects\fody\Fody\Processor.cs:line 48
Source:
Mono.Cecil
TargetSite:
Void ReadImage()
0:   Fody:   Finished Fody 23ms.

**Comment by GeertvanHorrik** [comment]
I believe this is caused by multiple solutions using a different version of Fody. All vs instances share the same msbuild instances, but it looks like you are using Fody 2.1 here.

**Comment by GeertvanHorrik** [comment]
Reverted back to the first commit which made changes to the FastObservableCollection, then the problem is not there. Checking which lines of code cause this issue.

**Comment by GeertvanHorrik** [comment]
Hmmm, looks like UWP (and maybe other platforms) can't really deal with single add events. When I change the code to this:

```
                        for (var i = 0; i < suspensionContext.Count; i++)
                        {
                            eventArgsList.Add(CreateEventArgs(NotifyCollectionChangedAction.Add, suspensionContext.NewItems[i], suspensionContext.NewItemIndices[i]));
                        }
```

It starts working again. But this breaks the whole point of using the FastObservableCollection.

**Comment by DanielKuehner** [comment]
I still do not get the "all vs instance" thing ... as long as does not matter for me, it will be ok ;)

You are using FOC in Catel.Fody? Is it possible to use just another collection?

Is there anything more I can help you with?

**Comment by GeertvanHorrik** [comment]
Oops, was commenting the wrong issue, sorry!

**Comment by DanielKuehner** [comment]
:-)

**Comment by DanielKuehner** [comment]
Is there anything more I can help you with?

**Comment by GeertvanHorrik** [comment]
I will try to work with the repro.

**Comment by DanielKuehner** [comment]
Ok. Tell me if I can help.

**Comment by GeertvanHorrik** [comment]
Going to try and check the repro on my system.

**Comment by GeertvanHorrik** [comment]
Also getting this one:

```
1>------ Rebuild All started: Project: GH0012, Configuration: Debug Any CPU ------
1>    Fody: Fody (version 2.1.2.0) Executing
1>      Fody/Catel:   Catel.Fody v2.17.0.0
1>      Fody/Catel:   Weaving properties
1>      Fody/Catel:   Weaving exposed properties
1>      Fody/Catel:   Weaving arguments
1>      Fody/Catel:   Weaving logging
1>      Fody/Catel:   Weaving xml schemas is disabled
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Value does not fall within the expected range.
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at Mono.Cecil.Pdb.ISymUnmanagedWriter2.DefineLocalVariable2(String name, Int32 attributes, Int32 sigToken, Int32 addrKind, Int32 addr1, Int32 addr2, Int32 addr3, Int32 startOffset, Int32 endOffset)
1>MSBUILD : error :    at Mono.Cecil.Pdb.NativePdbWriter.DefineScope(ScopeDebugInformation scope, MethodDebugInformation info, MetadataToken& import_parent)
1>MSBUILD : error :    at Mono.Cecil.Pdb.NativePdbWriter.Write(MethodDebugInformation info)
1>MSBUILD : error :    at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
1>MSBUILD : error :    at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddTypes()
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.BuildTypes()
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.BuildModule()
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>MSBUILD : error :    at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>MSBUILD : error :    at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
1>MSBUILD : error :    at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>MSBUILD : error :    at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>MSBUILD : error :    at InnerWeaver.WriteModule() in C:\Code\Fody\Fody\FodyIsolated\ModuleWriter.cs:line 18
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\Code\Fody\Fody\FodyIsolated\InnerWeaver.cs:line 89
1>MSBUILD : error : Source:
1>MSBUILD : error : Mono.Cecil.Pdb
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void DefineLocalVariable2(System.String, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32)
1>MSBUILD : error : 
1>    Fody:   Finished Fody 547ms.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

```

**Comment by GeertvanHorrik** [comment]
I think this is because Catel automatically cleans up the display info class (which is no longer required and it's best if it gets removed for performance & allocations). We probably need to remove it from the debug info as well. Will investigate.

**Comment by GeertvanHorrik** [comment]
Please try Catel.Fody 2.17.1

**Comment by DanielKuehner** [comment]
I have recreated the old error, reproduced it with 2.17.0, updated to 2.17.1 and the error was gone.
Great work, thanks!
