### ISSUE TITLE
Impossible to use with .NET Framework 4.5.2

### ISSUE THREAD

**Issue by SebastienDegodez** [Catel/Catel.Fody#14]
### Steps to reproduce

1. Install Catel.Fody > 2.17.0 on .Net 4.5.2 Project
2. Use NotNull Attribute (for example)

Platform: Windows
.NET version: 452

### Actual behaviour

I think the NuGet package is bad.
.NetStandard 1.0 is implemented in NET45 and higher.
https://docs.microsoft.com/en-gb/dotnet/standard/net-standard

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, we'll look into this.

**Comment by SimonCropp** [comment]
what version of nuget are you using?

**Comment by GeertvanHorrik** [comment]
Fixed in upcoming 3.0 release.
