### ISSUE TITLE
Weave calculated property notifications as if-else-if, not consecutive ifs

### ISSUE THREAD

**Issue by bigworld12** [Catel/Catel.Fody#174]
## Summary
change the way calculated properties are weaved to short-circuit using nested ifs
currently ,
Weaving readonly properties will place multiple IF statements in `OnPropertyChanged`
like so :
```cs
if (e.PropertyName.Equals("X"))
{
	base.RaisePropertyChanged("Y");
}
if (e.PropertyName.Equals("Z"))
{
	base.RaisePropertyChanged("Y");
}
if (e.PropertyName.Equals("H"))
{
	base.RaisePropertyChanged("B");
}
if (e.PropertyName.Equals("A"))
{
	base.RaisePropertyChanged("C");
}
```

## API Changes
make the method short-circuit if it finds a suitable match, e.g.

```cs
if (e.PropertyName.Equals("X"))
{
	base.RaisePropertyChanged("Y");
}
else if (e.PropertyName.Equals("Z"))
{
	base.RaisePropertyChanged("Y");
}
else if (e.PropertyName.Equals("H"))
{
	base.RaisePropertyChanged("B");
}
else if (e.PropertyName.Equals("A"))
{
	base.RaisePropertyChanged("C");
}
```

## Intended Use Case
This way it won't have to check every possible property name when it finds it early

**Comment by GeertvanHorrik** [comment]
I am not sure how the weaver works when there are multiple properties, e.g.:

```
public int Y
{
    get { return X + B; }
}

public int Z
{
    get { return X + B; }
}
```

Will Catel.Fody correctly weave the change notifications for both Y and Z in a single if statement?

**Comment by bigworld12** [comment]
oh i didn't think of this use case
it should weave them into a single if statement, i think

**Comment by GeertvanHorrik** [comment]
At this stage, I think it's too complex to implement where I don't see direct benefit. I did implement RaisePropertyChanged(() => property) yesterday though
