### ISSUE TITLE
Expose all Members of a model

### ISSUE THREAD

**Issue by TimKras** [Catel/Catel.Fody#18]
### Expose all Members of a model

Is there a way to expose all member of a model without including each member with the [Expose()] attribute?

https://catelproject.atlassian.net/wiki/spaces/CTL/pages/1409276/Exposing+properties+of+a+model+automatically

**Comment by GeertvanHorrik** [comment]
At the moment we don't have that option, are you sure you really want to expose them all (since this could be a lot and every property that you don't need will have an "impact" on performance).

It could be implemented in Catel.Fody though.
