### ISSUE TITLE
CatelFodyNullException with IEquatable implemented in another assembly

### ISSUE THREAD

**Issue by lipchev** [Catel/Catel.Fody#274]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [x] .NET Standard
 - [ ] .NET Core

## Component

Catel.Fody / Fody 

## Version of Library

Tested with 
Catel.Core 5.12.9 + Catel.Fody v4.4.0.0 + Fody 6.2.4 
Catel.Core 5.12.10 + Catel.Fody v4.4.0.0 + Fody 6.2.4 
Catel.Core 5.12.10 + Catel.Fody v4.5.0.0 + Fody 6.2.4 
Catel.Core 5.12.10 + Catel.Fody v4.5.0.0 + Fody 6.3.0  

## Version of OS(s) listed above with issue

win 10, net472

## Steps to Reproduce
1. Create a generic class (i.e. [KeyValuePair<T,V>](https://github.com/lipchev/CatelFodyNullException/blob/da1d1b5de445bff5be1cf36fa91796b9720edd62/DomainLib/KeyValuePair.cs#L5)) in one project & implement two interfaces involving the type parameters- one of which (I'm pretty sure) should be the IEquatable<Self> 
2. Create a concrete class in a second assembly, erasing the type parameters (e.g. [MyPair](https://github.com/lipchev/CatelFodyNullException/blob/da1d1b5de445bff5be1cf36fa91796b9720edd62/CatelFodyNullException/MyPair.cs#L8))
3. Host the extended object in a class extending [ModelBase](https://github.com/lipchev/CatelFodyNullException/blob/da1d1b5de445bff5be1cf36fa91796b9720edd62/CatelFodyNullException/MyModel.cs#L5) (in the second assembly).

## Expected Behavior

2>      Fody/Catel:   			MyModel - adding static constructor
2>      Fody/Catel:   			MyModel - added static constructor
2>      Fody/Catel:   			MyPair - adding GetValue call
2>      Fody/Catel:   			MyPair - adding SetValue call
Property change

## Actual Behavior

The build fails with a NullException
`Fody/Catel: Object reference not set to an instance of an object.	CatelFodyNullException`

Having either the KeyValuePair (base class) created in the local assembly, or removing one of the interfaces of the base class resolves the issue..

[Here ](https://github.com/lipchev/CatelFodyNullException)is a simple reproduction (using the current latest versions of each library)

**Comment by GeertvanHorrik** [comment]
Fantastic repro. Created unit tests around this, can repro:

![image](https://user-images.githubusercontent.com/1246444/103644869-60388d00-4f57-11eb-9d0b-42655d3a5928.png)

Trying to implement a fix.

**Comment by GeertvanHorrik** [comment]
I think the issue is a generic inside a generic:

```
System.IEquatable`1<Catel.Fody.TestAssembly.Bugs.GH0274.KeyValuePair`2<TKey,TValue>>
```

**Comment by GeertvanHorrik** [comment]
Finally fixed, was harder than I anticipated, but it's working now.
