### ISSUE TITLE
Catel.Fody doesn't weave the virtual properties correctly 

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel.Fody#291]
[Catel.Fody.Repro.zip](https://github.com/Catel/Catel.Fody/files/5679450/Catel.Fody.Repro.zip)

 - [x] .NET Core

## Component

Catel.Fody weaving properties
## Version of Library
4.5.0

## Version of OS(s) listed above with issue
win 10

## Steps to Reproduce
use the attached repro. 

## Expected Behavior
properties declared as virtual should also be included in OnPropertyChanged if they have been used in a calculation property.

## Actual Behavior
only not virtual properties will be included in OnPropertyChanged

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. We will investigate once we have resources available.

**Comment by GeertvanHorrik** [comment]
Trying to write unit tests around this repro.

**Comment by GeertvanHorrik** [comment]
can repro with unit test.

**Comment by GeertvanHorrik** [comment]
Fixed.
