### ISSUE TITLE
Catel.Fody Fails to weave properties that are referenced across multiple projects

### ISSUE THREAD

**Issue by xaecors** [Catel/Catel.Fody#295]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [x] .NET Standard
 - [ ] .NET Core

## Component

Catel.Fody

## Version of Library

- Catel.Fody: 4.6.0
- Catel.Core: 5.12.11
- Catel.MVVM: 5.2.11

## Version of OS(s) listed above with issue

Windows 10 20H2

## Steps to Reproduce

Sample solution has been attached ([WpfApp2.zip](https://github.com/Catel/Catel.Fody/files/5789189/WpfApp2.zip))

## Expected Behavior

Property weaving should complete successfully as designed in release 4.5.0

## Actual Behavior

Numerous exceptions are thrown:

```
1>MSBUILD : error : Fody/Catel: Type 'System.CodeDom.Compiler.GeneratedCodeAttribute' cannot be found, please report this bug
1>MSBUILD : error : Fody/Catel: Type 'System.Runtime.CompilerServices.CompilerGeneratedAttribute' cannot be found, please report this bug
1>MSBUILD : error : Fody/Catel: Type 'System.Diagnostics.DebuggerNonUserCodeAttribute' cannot be found, please report this bug
1>MSBUILD : error : Fody/Catel: Type 'System.ComponentModel.PropertyChangedEventArgs' cannot be found, please report this bug
1>MSBUILD : error : Fody/Catel: Type 'Void' cannot be found, please report this bug
1>MSBUILD : error : Fody/Catel: 		Failed to handle property 'PersonModel.BirthDate'
```

## Additional Notes

Rolling back to release 4.5.0 is the current workaround. It appears the issue may have been introduced as a side effect of #274 (or possibly #291)

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. For now please stick with 4.5 while we can look into this issue somewhere next week.

**Comment by GeertvanHorrik** [comment]
Fixed
