### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel.Fody#314]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component
 
Catel/Fody

## Version of Library

Custom build from latest release in the case of orchestra (Mahapps + fluent, instead of one or the other)  otherwise standard latest release. 

## Version of OS(s) listed above with issue
All the OS's

## Steps to Reproduce
1. Fork/Clone Wolvenkit at : https://github.com/WolvenKit/Wolvenkit (DEV BRANCH)
2. regular steps to open a project / restore nugets.
3. build&run.  get error. 

## Expected Behavior
Press green button once to build and run the debug.

## Actual Behavior
Need to press green button twice always.

**Comment by GeertvanHorrik** [comment]
Originally reported as https://github.com/Catel/Catel/issues/1766

**Comment by GeertvanHorrik** [comment]
Trying to repro with the latest prerelease of Catel.Fody. First build result:

![image](https://user-images.githubusercontent.com/1246444/108093362-f21ad600-707d-11eb-85a5-4bb6efa8bf56.png)

**Comment by GeertvanHorrik** [comment]
Btw very impressive app with use of Catel / Orc components, well done.

**Comment by GeertvanHorrik** [comment]
@Offline-R503B, could you please try Catel.Fody Build - 4.7.0-alpha.115 ? I could not reproduce the issue with that specific version.

**Comment by Offline-R503B** [comment]
@GeertvanHorrik Going to check! :) Thanks so far 👍  Will keep you posted.

**Comment by Offline-R503B** [comment]
![image](https://user-images.githubusercontent.com/11785451/108094675-58542880-707f-11eb-9f94-8cad717b24b4.png)
I only see these builds available on nuget ?

**Comment by GeertvanHorrik** [comment]
Yes, could be caching :)

https://www.nuget.org/packages/Catel.Fody/4.7.0-alpha0115

**Comment by Offline-R503B** [comment]
So at first try it didnt seem to do much, Made the decision to remove the old packages from the folder (Sometimes nuget is a little bit special.) Restarted visual studio.

And poof it works now 💯  (I did have a few warnings at first build but those were regarding me doing a Clean + rebuild , second build no more warnings)

Thanks a lot and i've forwarded your kind words about the app ❤️

**Comment by GeertvanHorrik** [comment]
Thanks for reporting back, glad the issue has been resolved. Let us know if you hit any other issues with Catel / Orc, we are happy to help out.
