### ISSUE TITLE
Part 2 of Object Reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Offline-R503B** [Catel/Catel.Fody#315]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?
Catel/Fody

## Version of Library
Latest Prerelease as advised.

## Version of OS(s) listed above with issue
Mostly W10 (I am not sure if we have users on W7)

## Steps to Reproduce
1. Fork /clone Wolvenkit 
2. Make some changes. *launch* 
3. result

## Expected Behavior
No Fody errors

## Actual Behavior
The error still pops when making changes in the project and then building it again. 

Rerunning build after this will make it launch without issues.

During Github build this issue is maybe a bit clearer to see :
https://github.com/WolvenKit/Wolvenkit/runs/1914026534#step:6:1094

**Comment by Offline-R503B** [comment]
Please note the other errors regarding textlib were on my side and unrelevant to the situation :)

**Comment by GeertvanHorrik** [comment]
Fixed, closing this ticket.
