### ISSUE TITLE
ViewModelBase derived classes with own SetValue method generating wrong code

### ISSUE THREAD

**Issue by SelvinPL** [Catel/Catel.Fody#361]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ x] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?
Catel/Fody

## Version of Library
4.7.0

## Steps to Reproduce
1. Use code llike this and check what it generate (problem is `VM.SetValue` of course)

```
    public class VM : ViewModelBase
    {
        [Model]
        public Test Test { get; set; }
        [ViewModelToModel]
        public string Prop { get; set; }

        public void SetValue(string a)
        {

        }
    }

    public class Test
    {
        public string Prop { get; set; }
    }
```

## Expected Behavior

It should generate right code 

## Actual Behavior

it generates gibberish:

```
	[Model]
	public Test Test
	{
		[CompilerGenerated]
		get
		{
			return GetValue<Test>(TestProperty);
		}
		[CompilerGenerated]
		set
		{
			//IL_000d: Expected O, but got I4
			_ = TestProperty;
			((ViewModelBase)(object)value).SetValue<!!0, !!1, !!2>((!!0)1);
		}
	}

	[ViewModelToModel("", "")]
	public string Prop
	{
		[CompilerGenerated]
		get
		{
			return GetValue<string>(PropProperty);
		}
		[CompilerGenerated]
		set
		{
			//IL_000d: Expected O, but got I4
			_ = PropProperty;
			((ViewModelBase)(object)value).SetValue<!!0, !!1, !!2>((!!0)1);
		}
	}
```

which finally leads to `System.MissingMethodException: 'Method not found: 'Catel.Data.PropertyData Catel.MVVM.ViewModelBase.SetValue(!!0)'.'` with code

`new VM().Test = new Test { Prop = "Whatever"};`

**Comment by GeertvanHorrik** [comment]
Thanks for reporting! We will try to work on this for the next release.

If you want, you can help out by either creating a PR (even if it's only the unit test, we can do the other implementations) or by considering supporting the open collective.

**Comment by SelvinPL** [comment]
Ho should I name commit ?

**Comment by GeertvanHorrik** [comment]
To create a pull request, you would have to create a fork (right top button in GitHub). Then I personally prefer to create a separate branch (e.g. pr/setvalue-fix) and feel free to name the commits whatever feels right.

Once the PR is in place, we can commit to it as well and finalize the feature.

**Comment by SelvinPL** [comment]
I did only Unit test

**Comment by GeertvanHorrik** [comment]
That's perfect. If you can create the fork + branch + unit test, we can implement the fix. We will merge once it's fully complete.

**Comment by GeertvanHorrik** [comment]
A good commit name could be: "Add unit test for SetValue override selection issue"

**Comment by GeertvanHorrik** [comment]
Closing as this is now fixed.
