### ISSUE TITLE
Can anyone please help me how to use Costura.Fody to package LevelDB.Standard ? 

### ISSUE THREAD

**Issue by AtlantisDe** [Catel/Catel.Fody#412]
Can anyone please help me how to use Costura.Fody to package LevelDB.Standard ? Got this error System.TypeInitializationException: ""LevelDB.LevelDBInterop" This is the Demo code I made for reference. matjazbravc/Embedded-SQLite-Demo#1

ths very much

**Comment by GeertvanHorrik** [comment]
This is not Catel.Fody related, so closing this issue.

**Comment by AtlantisDe** [comment]
My temporary plan is this
If there is no other solution, I will close this issue in the next 5 days

var dllHandle = LoadLibrary("leveldb.dll");
