### ISSUE TITLE
"The weaver needs to add a NuGet reference" in build

### ISSUE THREAD

**Issue by fmongeau** [Catel/Catel.Fody#7]
Hello. Apologies if this is not the right place to post this - I haven't found any place to get help. 
I updated the NuGet packages for my project and now I get:
```
Fody: Fody (version 2.0.2.0) Executing
MSBUILD : error : Fody: The weaver assembly 'Catel.Fody, Version=2.15.0.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll (cecilReference.Version). At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0.2.0.
```
... is this something I can fix on my end ? If so how? Thanks.

**Comment by GeertvanHorrik** [comment]
The authors of Fody released Fody 2.0 yesterday which is a breaking change. We need to update (but since it was released yesterday, we haven't found time for it just yet). For the time being you should downgrade Fody (because other weavers you might be using a probably not updated as well).

**Comment by GeertvanHorrik** [comment]
Closing as duplicate, see #6

**Comment by GeertvanHorrik** [comment]
@fmongeau thanks for reporting, we will fix as soon as possible. If you hit any other issues, please report them again.

**Comment by GeertvanHorrik** [comment]
You can check out Build - 2.16.0-unstable.3. If you find any issues with this version, please report asap.

**Comment by UweKeim** [comment]
Getting the same for a rather old project of mine, this is the output:

```
1>------ Build started: Project: ZetaFileSync.PublicRuntime, Configuration: Release Any CPU ------
1>    Fody: Fody (version 3.2.5.0) Executing
1>    Fody: Searched for 'ModuleInit'. Found: C:\P\ZetaFileSync\Source\packages\ModuleInit.Fody.1.5.9.0\ModuleInit.Fody.dll
1>MSBUILD : error : Fody: The weaver assembly 'ModuleInit.Fody, Version=1.5.9.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll 0.9.6.0. At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 3.0.
1>    Fody:   Finished Fody 365ms.
========== Build: 0 succeeded, 1 failed, 5 up-to-date, 0 skipped ==========
```

The core error message is:

> MSBUILD : error : Fody: The weaver assembly 'ModuleInit.Fody, Version=1.5.9.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll 0.9.6.0. At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 3.0.

I've tried to add a reference, but found no "FodyCecil version 3.0", just v2.4.5.

Any idea how to fix this?

**Comment by GeertvanHorrik** [comment]
@UweKeim

**Comment by UweKeim** [comment]
Thanks, [I've posted this on the Fody page](https://github.com/Fody/Fody/issues/559) and they just released a bug fix.
