### ISSUE TITLE
BadImageFormatException with Expose - weaver cannot resolve type of property

### ISSUE THREAD

**Issue by SelvinPL** [Catel/Catel.Fody#99]
I'm not sure if it's bug in Catel.Fody or Fody/Mono itself but I'm getting 
>BadImageFormatException: Próbowano załadować program w niepoprawnym formacie. 

with code

```
namespace CatelFodyBug
{
    using Catel.Fody;
    using Catel.MVVM;
    using System.Collections.Generic;

    public class TestViewModel : ViewModelBase
    {
        [Model]
        [Expose("ID")]
        public Model Model { get; set; }

        public static void Main(string[] args)
        {
            var vm = new TestViewModel();
        }
    }

    public class Model : BaseModel<Model>
    {
        
    }

    public class BaseModel<T> : EntityBaseWithID<int, T> where T: BaseModel<T>
    {

    }

    public class EntityBaseWithID<T, S>  where S : EntityBaseWithID<T, S>
    {
        public T ID { get; set; }

        //this is why I'm using S
        public override bool Equals(object other)
        {
            if (other is S n)
                return n.ID.Equals(ID);
            return false;
        }

        //irrelevant for this example
        public override int GetHashCode()
        {
            var hashCode = 509650306;
            hashCode = hashCode * -1521134295 + EqualityComparer<T>.Default.GetHashCode(ID);
            hashCode = hashCode * -1521134295 + GetType().GetHashCode();
            return hashCode;
        }
    }
}
```

obviously it's because generated code is wrong

```
public static readonly Catel.Data.PropertyData IDProperty = Catel.Data.ModelBase.RegisterProperty("ID", typeof(!0));
	public !0 ID
	{
		get..
		set..
	}

```
seems like weaver can't resolve generic type

**Comment by GeertvanHorrik** [comment]
Great repro, this is how we want repros to be, was able to reproduce and integrate as unit test. Now the "only" thing left is to actually fix it :)

**Comment by GeertvanHorrik** [comment]
If I understand correctly, you expect T to be of type Model?

**Comment by GeertvanHorrik** [comment]
No, I see it now, it should be int. Need to improve the logic to resolve the generics a bit.

**Comment by GeertvanHorrik** [comment]
@SelvinPL please try Build - 4.1.0-alpha.69 (ETA 20 minutes on NuGet), should work now. I haven't tested redefined complex generics where, for example T, is renamed to a different parameter name higher up the tree. I would say that would be very confusing to end developers anyway, so consider this is as "not supported".

**Comment by SelvinPL** [comment]
Yes, it shoudl be int ... unfortunatelly I used T in derrived class in different place

**Comment by GeertvanHorrik** [comment]
The test case you provided succeeds, so should be ok ;-)

**Comment by GeertvanHorrik** [comment]
Should be available here whenever NuGet is ready:

https://www.nuget.org/packages/Catel.Fody/4.1.0-alpha0069

**Comment by SelvinPL** [comment]
Is it a flaw of Mono.Cecil? I'm pretty sure that System.Reflection would return right type

**Comment by GeertvanHorrik** [comment]
No, Catel.Fody has to determine the actual (final) type of the generic argument used (based on name and index in the hierarchy tree). I have implemented this method, but it's "simple", might not support all use-cases. Anyway, you will notice when it doesn't work (would still result in BadImageException or cast exceptions), so we can look into it when we really have to.

**Comment by GeertvanHorrik** [comment]
If you can let me know whether it's fixed, then I can release it as stable.

**Comment by SelvinPL** [comment]
Ok, now it's working :)

**Comment by GeertvanHorrik** [comment]
Thanks, will deploy stable 4.1 now.
